services:
  nyrkes_ci:
    container_name: nyrkes_ci
    image: nyrkes_ci_image
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.local
    volumes:
      - .:/usr/nyrkes
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      - NYRKES_ENVIRONMENT=local
      - ENV_FILE=.env
    depends_on:
      - postgres_ci
    restart: unless-stopped
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  postgres_ci:
    container_name: postgres_ci
    image: postgres:latest
    volumes:
      - postgres_ci:/var/lib/postgresql/data/
    env_file:
      - ./../.env
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  postgres_ci:
