services:
  nyrkes:
    container_name: nyrkes_local
    image: nyrkes_local_image
    build:
      context: .
      dockerfile: docker/Dockerfile.local
    volumes:
      - .:/usr/nyrkes-backend
    env_file:
      - .env.local
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      - NYRKES_ENVIRONMENT=local
      - ENV_FILE=.env.local
    depends_on:
      - postgres_local
    restart: unless-stopped
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  postgres_local:
    container_name: postgres_local
    image: postgres:latest
    volumes:
      - postgres_local:/var/lib/postgresql/data/
    env_file:
      - .env.local
    ports:
      - 5432:5432
    restart: unless-stopped

  pgadmin_local:
    container_name: pgadmin4_local
    image: dpage/pgadmin4
    ports:
      - 5555:80
    volumes:
      - pgadmin4_local:/var/lib/pgadmin
    env_file:
      - .env.local
    logging:
      driver: "none"
    depends_on:
      - postgres_local
    restart: unless-stopped

  redis_local:
    container_name: redis_local
    image: redis:7.0.4-alpine
    volumes:
      - ./config/settings/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_local:/bitnami/redis/data
    ports:
      - 6379:6379
    env_file:
      - .env.local
    logging:
      driver: "none"
    depends_on:
      - postgres_local
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.local
    volumes:
      - .:/usr/nyrkes-backend
    env_file:
      - .env.local
    environment:
      - NYRKES_ENVIRONMENT=local
      - ENV_FILE=.env.local
    restart: always
    command: celery -A nyrkes worker -l info
    depends_on:
      - postgres_local
      - redis_local
      - nyrkes

volumes:
  postgres_local:
  pgadmin4_local:
  redis_local:
