# Generated by Django 4.1.3 on 2022-11-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menel", "0002_organization_organizationmember_organization_members_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="organizationmember",
            name="user_organization_unique",
        ),
        migrations.RemoveField(
            model_name="organizationmember",
            name="invited_by",
        ),
    ]
