# Generated by Django 4.1.3 on 2022-12-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nyrkes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
    ]
